<a href="https://colab.research.google.com/github/bipu01/machineLearning/blob/main/MachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction To numpy
1. Creating single dimentional arrays ✅
2. Multidimentional array ✅



In [1]:
import numpy as np

In [3]:
# creating an array with all zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# creating an array with all elements 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
# creating an array of size 10 with elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [8]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [10]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
# create an array wut evenly spaced numbers within a specified range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multidimentional array

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Defining multidimentional array and editing

In [44]:
three_by_three_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
three_by_three_array[0, 1] = 20
three_by_three_array



array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [45]:
three_by_three_array[2] = [1, 1, 1]
three_by_three_array

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [47]:
three_by_three_array[:, 2] = [2, 2, 2]
three_by_three_array

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [57]:
new_array = np.full((3, 3), 10)
new_array

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Randomly Generated arrays

- Numpy can create arrays filled with random numbers
- To ensure the reproducibility, you can set a seed using ``` np.random.seed()```. It will generate the exact same random numbers for each executions.
- If you remove or change the seed values, the sequence of random numbers will be changed.

In [60]:
random_array = np.random.rand(5)
random_array

array([0.74070246, 0.72654919, 0.52209105, 0.54852156, 0.42206096])

In [66]:
np.random.seed(5)
np.random.rand(5)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

In [71]:
np.random.randn(5, 2)

array([[-1.38469452, -0.11209336],
       [ 0.40226978, -0.05558717],
       [-0.99798236,  0.05019618],
       [ 1.19200034,  1.3835964 ],
       [-0.24585362,  0.052122  ]])

In [79]:
np.random.randint(low = 0, high = 100, size = (5, 3))

array([[ 6,  7, 35],
       [78,  9,  7],
       [89, 90, 54],
       [31, 14,  4],
       [85, 74, 68]])